version: "3.9"

services:
  service:
    env_file: 
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medpet-chatbot-service
    volumes: 
      - ".:/usr/src/app"
    ports:
      - "3000:3000"